serverinfo:
  servertag:
    "§f[§6SERV§f] "
  info:
    "§f[§6INFO§f] "
  ip:
    "play.novauhc.fr"
  servername:
    "§cSERVER"
  helpop:
    "§f[§6HELP§f] "
api:
  url: "http:
  key: "TA CLEF API ICI"
  server-name: "Nova-UHC"
mumble:
  port: ""
  ip: ""
doc: "https:
discord: "https:
staff:
  - "89daecd6-f9a7-4a2e-a8bf-a7d9294f074f"
## PlaceHolder utilisable :

